---
trigger:
  - master
jobs:
  - job: "Test"
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      matrix:
        precommit:
          python.version: "3.8"
          tox.env: precommit
        stories-upgrade:
          python.version: "3.8"
          tox.env: stories-upgrade
        flake8:
          python.version: "3.8"
          tox.env: flake8
        bandit:
          python.version: "3.8"
          tox.env: bandit
        xenon:
          python.version: "3.8"
          tox.env: xenon
        mypy:
          python.version: "3.8"
          tox.env: mypy
        vale:
          python.version: "3.8"
          tox.env: vale
        remarklint:
          python.version: "3.8"
          tox.env: remarklint
        yamllint:
          python.version: "3.8"
          tox.env: yamllint
        jscpd:
          python.version: "3.8"
          tox.env: jscpd
        commitlint:
          python.version: "3.8"
          tox.env: commitlint
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
        displayName: Install Python.
      - script: pip install --upgrade tox codecov
        displayName: Install Tox.
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        condition: in(variables['tox.env'], 'remarklint', 'jscpd')
        displayName: Install NodeJS.
      - script: |
          curl https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh
          echo '##vso[task.prependpath]$(system.defaultWorkingDirectory)/bin'
        condition: in(variables['tox.env'], 'vale')
        displayName: Install Vale.
      - script: |
          git remote set-branches origin master
          git fetch --unshallow --quiet
          git checkout master --quiet
          git checkout - --quiet
        condition: in(variables['tox.env'], 'commitlint')
        displayName: Unshallow commit log.
      - script: tox -e $(tox.env)
        displayName: Run Tox.
      - script: |
          if [ -f .coverage ]
          then
            codecov
          fi
        env:
          CODECOV_TOKEN: 8e234fd6-9c31-43f0-b915-38e4ba9d941e
        displayName: Report Coverage.
